# Generated by Django 3.2.5 on 2021-08-06 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmTB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cm_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GenreTB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=200)),
                ('cm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moticom.cmtb')),
            ],
        ),
        migrations.CreateModel(
            name='UserTB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('email_adress', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('pw_digest', models.CharField(max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='ReportTB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moticom.genretb')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moticom.usertb')),
            ],
        ),
        migrations.CreateModel(
            name='LikeTB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moticom.reporttb')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moticom.usertb')),
            ],
        ),
        migrations.CreateModel(
            name='BadTB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moticom.reporttb')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moticom.usertb')),
            ],
        ),
    ]
