# Generated by Django 3.2.5 on 2021-08-06 15:36

from django.db import migrations


class Migration(migrations.Migration):
    
    atomic = False
    
    dependencies = [
        ('moticom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BadTB',
            new_name='Bad',
        ),
        migrations.RenameModel(
            old_name='CmTB',
            new_name='ControlMeasure',
        ),
        migrations.RenameModel(
            old_name='GenreTB',
            new_name='Genre',
        ),
        migrations.RenameModel(
            old_name='LikeTB',
            new_name='Like',
        ),
        migrations.RenameModel(
            old_name='ReportTB',
            new_name='Report',
        ),
        migrations.RenameModel(
            old_name='UserTB',
            new_name='User',
        ),
    ]
