# Generated by Django 3.2.6 on 2021-11-22 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moticom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='cm_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moticom.controlmeasure'),
        ),
    ]
