# Generated by Django 3.2.5 on 2021-08-06 15:47

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False
    
    dependencies = [
        ('moticom', '0002_auto_20210807_0036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='BadTB',
        ),
        migrations.RenameModel(
            old_name='ControlMeasure',
            new_name='CmTB',
        ),
        migrations.RenameModel(
            old_name='Genre',
            new_name='GenreTB',
        ),
        migrations.RenameModel(
            old_name='Bad',
            new_name='LikeTB',
        ),
        migrations.RenameModel(
            old_name='Report',
            new_name='ReportTB',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='UserTB',
        ),
    ]
