# Generated by Django 3.2.6 on 2021-12-01 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moticom', '0003_like_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_words', models.CharField(max_length=30)),
                ('cm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moticom.controlmeasure')),
            ],
        ),
    ]
