# Generated by Django 3.2.6 on 2021-10-25 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moticom', '0005_remove_genre_cm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlmeasure',
            name='cm_contents',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='controlmeasure',
            name='genre_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='moticom.genre'),
            preserve_default=False,
        ),
    ]
