# Generated by Django 3.2.6 on 2021-12-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moticom', '0005_report_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
