# Generated by Django 3.2.6 on 2021-10-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moticom', '0006_auto_20211025_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='comment',
            field=models.CharField(default='', max_length=300),
        ),
    ]
