# Generated by Django 3.2.6 on 2021-10-27 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moticom', '0007_report_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='comment',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moticom.report')),
            ],
        ),
    ]
