# Generated by Django 3.2.6 on 2021-11-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moticom', '0008_auto_20211027_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ng_words', models.CharField(max_length=30)),
            ],
        ),
    ]
