# Generated by Django 3.2.8 on 2021-11-17 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moticom', '0009_ngword'),
        ('moticom', '0010_remove_like_timestamp'),
    ]

    operations = [
    ]
