# Generated by Django 3.2.8 on 2021-11-18 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moticom', '0005_auto_20211109_1123'),
        ('moticom', '0012_remove_like_like'),
    ]

    operations = [
    ]
